### ISSUE TITLE
Make a new release v.1.4

### ISSUE THREAD

**Issue by rytisder** [amirkhiz/resellerclub-php-api#13]
After a couple of bug fixes and Actions API introduced, it would be great to have it on Packagist.

https://packagist.org/packages/habil/resellerclub-php-api#v1.3.10

**Comment by rytisder** [comment]
@amirkhiz

**Comment by amirkhiz** [comment]
Yes, you are right @rytisder. I will do it today promises :).

**Comment by amirkhiz** [comment]
@rytisder I released new version please check this out and let me know if there is any problem. :)
I am closing this issue.

**Comment by rytisder** [comment]
Everything works! 🚀
