### ISSUE TITLE
Laravel 5.6 issue

### ISSUE THREAD

**Issue by domainadmin** [amirkhiz/resellerclub-php-api#2]
Hello,

This does not work with the latest version of Laravel. Is there a work around?

**Comment by amirkhiz** [comment]
Hi,
Actually not yet but it could be done. If you want you can have a workaround. I'll try to work on that.

**Comment by rytisder** [comment]
I can confirm that it does work with Laravel 6.X and 7.X.

**Comment by rytisder** [comment]
@amirkhiz, I think you can close this issue. :)

**Comment by amirkhiz** [comment]
@rytisder thanks for your confirmation.
