### ISSUE TITLE
missing authentication data in POST requests

### ISSUE THREAD

**Issue by bitbybit** [amirkhiz/resellerclub-php-api#6]
https://github.com/afbora/resellerclub-php-sdk/pull/3

**Comment by amirkhiz** [comment]
@bitbybit I'm using authentication in POST requests, You can check it here.
https://github.com/amirkhiz/resellerclub-php-api/blob/master/src/Helper.php#L82

**Comment by bitbybit** [comment]
Sorry then. I didn't notice :+1:

**Comment by amirkhiz** [comment]
It's ok ;)
